# Generated by Django 5.1.6 on 2025-09-24 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('api_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='接口ID')),
                ('api_name', models.CharField(max_length=100, verbose_name='接口名称')),
                ('api_request_type', models.CharField(max_length=10, verbose_name='请求方式')),
                ('api_request_url', models.CharField(max_length=300, verbose_name='请求地址')),
                ('api_url_params', models.TextField(verbose_name='请求参数(get)')),
                ('api_post_data', models.TextField(verbose_name='提交数据(post)')),
            ],
            options={
                'verbose_name': '接口信息',
                'verbose_name_plural': '接口信息',
                'db_table': 'api_info',
            },
        ),
        migrations.CreateModel(
            name='CaseInfo',
            fields=[
                ('case_info_id', models.CharField(db_column='CaseInfo_id', max_length=10, primary_key=True, serialize=False, verbose_name='用例信息ID')),
                ('case_id', models.CharField(max_length=10, verbose_name='测试用例编号')),
                ('case_name', models.CharField(max_length=100, verbose_name='测试用例名称')),
                ('is_run', models.CharField(default='是', max_length=4, verbose_name='用例执行')),
            ],
            options={
                'verbose_name': '用例信息',
                'verbose_name_plural': '用例信息',
                'db_table': 'case_info',
            },
        ),
        migrations.CreateModel(
            name='CaseStepInfo',
            fields=[
                ('case_step_info_id', models.CharField(db_column='CaseStepInfo_id', max_length=10, primary_key=True, serialize=False, verbose_name='步骤ID')),
                ('case_id', models.CharField(max_length=10, verbose_name='测试用例编号')),
                ('case_step_name', models.CharField(max_length=20, verbose_name='测试用例步骤')),
                ('part_name', models.CharField(max_length=255, verbose_name='模块名称')),
                ('get_value_type', models.CharField(max_length=20, verbose_name='取值方式')),
                ('variable_name', models.CharField(max_length=20, verbose_name='传值变量')),
                ('excepted_result_type', models.CharField(max_length=20, verbose_name='期望结果类型')),
                ('excepted_result', models.TextField(verbose_name='期望结果')),
                ('is_pass', models.CharField(blank=True, max_length=255, null=True, verbose_name='是否通过')),
                ('get_value_code', models.TextField(blank=True, null=True, verbose_name='取值代码')),
                ('api', models.ForeignKey(db_column='api_id', on_delete=django.db.models.deletion.CASCADE, to='api_auto.apiinfo', verbose_name='关联接口')),
            ],
            options={
                'verbose_name': '用例步骤',
                'verbose_name_plural': '用例步骤',
                'db_table': 'case_step_info',
                'ordering': ['part_name', 'case_id', 'case_step_name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_chin_name', models.CharField(max_length=100, verbose_name='中文名称')),
                ('section', models.CharField(max_length=100, verbose_name='配置节')),
                ('key_name', models.CharField(max_length=100, verbose_name='键名')),
                ('value', models.TextField(verbose_name='键值')),
                ('note', models.CharField(max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '环境配置',
                'verbose_name_plural': '环境配置',
                'db_table': 'config_urls',
                'unique_together': {('section', 'key_name')},
            },
        ),
    ]
